services:
  api:
    build:
      context: .
    volumes:
      - ./app:/app
    expose:
      - "8000"
    environment:
      - PORT=8000

  pact_verifier:
    image: pactfoundation/pact-cli:latest@sha256:68a2a0b467b839c83abc802b39c84279c10b5ef1aa7758f1c4109f59b7f95841
    depends_on:
      - api
    environment:
      - PACT_BROKER_BASE_URL
      - PACT_BROKER_TOKEN
      - PACT_BROKER_USERNAME
      - PACT_BROKER_PASSWORD
      - PACT_BROKER_PUBLISH_VERIFICATION_RESULTS
      - PACT_URL
      - GIT_COMMIT
      - GIT_BRANCH
    command: >
      verify
      ${PACT_URL}
      --provider-base-url http://api:8000
      --provider pactflow-example-provider-python
      --provider-app-version ${GIT_COMMIT}
      --provider-version-branch ${GIT_BRANCH}
      --wait 10
  
  pact_verifier_native:
    image: pactfoundation/pact-ref-verifier:latest@sha256:c511079f839bf4f291534e36a416f03f4372660851ce4f2aeaffcfd3450e71cf
    depends_on:
      - api
    environment:
      - PACT_BROKER_BASE_URL
      - PACT_BROKER_TOKEN
      - PACT_BROKER_USERNAME
      - PACT_BROKER_PASSWORD
      - PACT_BROKER_PUBLISH_VERIFICATION_RESULTS
      # - PACT_WEBHOOK_CALLBACK_URL=${PACT_URL}
      - GIT_COMMIT
      - GIT_BRANCH
    command: >
      --hostname api
      --port 8000
      --provider-name pactflow-example-provider-python
      --loglevel info
      --provider-version $GIT_COMMIT
      --provider-branch $GIT_BRANCH