services:
  api:
    build:
      context: .
    volumes:
      - ./app:/app
    expose:
      - "8000"
    environment:
      - PORT=8000

  pact_verifier:
    image: pactfoundation/pact-cli:latest
    depends_on:
      - api
    environment:
      - PACT_BROKER_BASE_URL
      - PACT_BROKER_TOKEN
      - PACT_BROKER_USERNAME
      - PACT_BROKER_PASSWORD
      - PACT_BROKER_PUBLISH_VERIFICATION_RESULTS
      - PACT_URL
      - GIT_COMMIT
      - GIT_BRANCH
    command: >
      verify
      /pacts/pactflow-example-consumer-python-pactflow-example-provider-python.json
      --provider-base-url http://api:8000
      --provider pactflow-example-provider-python
      --log-level debug
      --wait 10
      --provider-states-setup-url http://api:8000/_pact/state
    volumes:
      - ./pacts_ruby:/pacts
  
  pact_verifier_native:
    image: pactfoundation/pact-ref-verifier:latest
    depends_on:
      - api
    environment:
      - PACT_BROKER_BASE_URL
      - PACT_BROKER_TOKEN
      - PACT_BROKER_USERNAME
      - PACT_BROKER_PASSWORD
      - PACT_BROKER_PUBLISH_VERIFICATION_RESULTS
      # - PACT_WEBHOOK_CALLBACK_URL=${PACT_URL}
      - GIT_COMMIT
      - GIT_BRANCH
    command: >
      --hostname api
      --port 8000
      --provider-name pactflow-example-provider-python-v3
      --loglevel info
      --dir /pacts
      --request-timeout 10000
      --state-change-url http://api:8000/_pact/state
    volumes:
      - ./pacts_rust:/pacts